### ISSUE TITLE
石川県が出している物と勘違いされる可能性がある(非公式感がない)

### ISSUE THREAD

**Issue by masebb** [Retsuki/covid19-ishikawa#1]
## 起こっている問題 / The Problem
- トップページだけを見ると、石川県が公式で出しているように見える。

## スクリーンショット / Screenshot
参考:https://stopcovid19.code4.nagoya/ (愛知県版)
![Screenshot_2020-03-30 愛知県 新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/30523995/78038672-0f807c00-73a8-11ea-8770-d81bdf2ea4d4.png)

## 期待する見せ方・挙動 / Expected Behavior
- 上記のスクリーンショットのように非公式とどこからでも非公式と認識できるようなものを置く

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Retsuki** [comment]
すみません、直ちに修正します！！

**Comment by Retsuki** [comment]
修正しました！
