### ISSUE TITLE
レポジトリのdescriptionとREADME.mdにサイトのURLがない

### ISSUE THREAD

**Issue by masebb** [Retsuki/covid19-ishikawa#3]
## 起こっている問題 / The Problem
- descriptionとREADME.md両方にこのサイトのURLがない(それっぽいやつが全部 https://www.pref.ishikawa.lg.jp/kansen/coronakennai.html になっている)

## 期待する見せ方・挙動 / Expected Behavior
- README.mdのサイトURLを```https://www.pref.ishikawa.lg.jp/kansen/coronakennai.html```から```https://ishikawa-covid19.netlify.com/```に変更する
- **descriptionに載っているURLを更新する**(管理者じゃないとできないので @Retsuki お願いします！)

**Comment by Retsuki** [comment]
ありがとうございます。
修正しました！！
