### ISSUE TITLE
カードをSNSにシェアしようとすると、サイト名が東京都のものになっている

### ISSUE THREAD

**Issue by kentaro-m** [Retsuki/covid19-ishikawa#5]
## 起こっている問題 / The Problem
- カードをSNSにシェアしようとすると、サイト名が`東京都新型コロナウイルス感染症対策サイト`になっている

## スクリーンショット / Screenshot

Twitterでシェアしたときの見え方
<img width="707" alt="スクリーンショット 2020-04-04 17 26 15" src="https://user-images.githubusercontent.com/7448569/78422325-726c5e80-7699-11ea-8e70-807f72e72fab.png">

Facebookでシェアしたときの見え方
<img width="546" alt="スクリーンショット 2020-04-04 17 27 39" src="https://user-images.githubusercontent.com/7448569/78422352-9b8cef00-7699-11ea-8529-3feae18d86b7.png">

LINEでシェアしたときの見え方
![IMG_0686-2](https://user-images.githubusercontent.com/7448569/78422417-10f8bf80-769a-11ea-8654-1c0c4b5e4d6c.png)

## 期待する見せ方・挙動 / Expected Behavior
- SNSにシェアされる際にサイト名が`石川県 新型コロナウイルス感染症対策サイト`になっていること

## 起こっている問題の再現手段 / Steps to Reproduce
1. [サイトトップページ](https://ishikawa-covid19.netlify.com/)にアクセス
1. 陽性患者の属性または陽性患者数のカードのシェアボタンを押下する
2. 各種SNS (LINE, Twitter, Facebook) に移動する

## 動作環境・ブラウザ / Environment
- macOS / iOS
- Chrome / Safari

**Comment by kentaro-m** [comment]
修正できそうなので、のちほどPRを作成しようと思います

**Comment by Retsuki** [comment]
ありがとうございました！！
Twitterに関してはこちらでも調べてみます！

**Comment by Retsuki** [comment]
> 修正できそうなので、のちほどPRを作成しようと思います

ありがとうございます！！

**Comment by Retsuki** [comment]
東京都のソースを基に直したところ、
Twitterのogpもしっかり表示されるようになりました！！
ご協力ありがとうございました！！

> 修正できそうなので、のちほどPRを作成しようと思います

東京都のソースを基に直したところ、
Twitterのogpもしっかり表示されるようになりました！！
ご協力ありがとうございました！！

追記
ogpテストサイトではうまくいってますが、
弊アカウントで共有した場合、うまくいっていない
キャッシュの問題？
似たようなissueが東京都の昔のissueにあったので調べてみる

**Comment by kentaro-m** [comment]
@Retsuki 
対応ありがとうございます！

TwitterのOGPのキャッシュですが、以下のサイトで該当のURLを入力して、「Preview card」をクリックすると、キャッシュがクリアされると思います。

https://cards-dev.twitter.com/validator

参考: [Twitterカードの画像やタイトルを新しく更新するキャッシュ削除方法 | iscle [イズクル]](https://www.iscle.com/web-it/twitter-card-cache.html)
