### ISSUE TITLE
感染者情報のスクレイピングについて

### ISSUE THREAD

**Issue by imabari** [Retsuki/covid19-ishikawa#7]
## 改善詳細 / Details of Improvement

感染者情報のスクレイピングのサンプルです
https://imabari.hateblo.jp/entry/2020/04/06/232203

よかったら使ってください

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Retsuki** [comment]
> ## 改善詳細 / Details of Improvement
> 感染者情報のスクレイピングのサンプルです
> https://imabari.hateblo.jp/entry/2020/04/06/232203
> 
> よかったら使ってください
> 
> ## 動作環境・ブラウザ / Environment
> * macOS / Windows / Linux / iOS / Android
> * Chrome / Safari / Firefox / Edge / Internet Explorer

丁寧なコードありがとうございます！！
やっと石川県のサイトがフォーマットを整えてくれて本当にありがたい限りですねww
でも、まだおかしな点があってh2タグと症状歴にある感染確認日が同じじゃないのがあって
僕としては症状歴の感染確認日を採用しています。
再度、そういった改善が見られたらimabariさんのコードを採用しますね
本当にありがとうございます！

**Comment by imabari** [comment]
他県でも公表日が基準になっています。

**Comment by Retsuki** [comment]
> 他県でも公表日が基準になっています。

本日より、石川県のサイトの方で「:」の文字列を扱い出したのをきっかけに
imabariさんのjaconvと正規表現を参考にさせていただきました。
ありがとうございます！
